site_name: TLC Documentation
theme: readthedocs
site_description: TLC IT Documentation Hub
site_author: TLC Companies IT Dept
site_url: https://tlcdoc.netlify.com/

extra:
  social:
    - type: 'github'
      link: ''
    - type: 'twitter'
      link: ''
    - type: 'facebook'
      link: ''
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: pink


extra_css:
  - 'stylesheets/extra.css'

repo_name: 'tlcMattLarson/mkdocs-cms-2'
repo_url: 'https://github.com/tlcMattLarson/mkdocs-cms-2'

# Copyright
copyright: '<a href="http://tlccompanies.com">TLC Companies</a>'

# Theme directory
theme_dir: readthedocs

docs_dir: docs

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - 'Home': 'index.md'
