site_name: Online-Dokumentationen
theme: readthedocs
site_description: A Material Design theme for MkDocs
site_author: Meinolf Droste
site_url: https://tlcdoc.netlify.com/

extra:
  social:
    - type: 'github'
      link: 'https://github.com/capriosa'
    - type: 'twitter'
      link: 'https://twitter.com/mdwp'
    - type: 'facebook'
      link: 'https://facebook.com/mdwp.de'
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: pink


extra_css:
  - 'stylesheets/extra.css'

repo_name: 'tlcMattLarson/mkdocs-cms-2'
repo_url: 'https://github.com/tlcMattLarson/mkdocs-cms-2'

# Copyright
copyright: '<a href="https://www.mdwp.de">mdwp</a>'

# Theme directory
#theme_dir: material

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.highlight

# Page tree
pages:
  - 'MkDocs-CMS': 'index.md'
