backend:
  name: github
  repo: tlcMattLarson/mkdocs-cms-2
  branch: master

public_folder: "/"
media_folder: "/assets"
publish_mode: editorial_workflow

collections:
  - name: "doc"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
  - name: "extensions"
    label: "Extensions"
    folder: "docs/extensions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
